import type { BenchmarkMetric, BudgetRecommendation, InsightItem, PeriodInsightData, PeriodKey } from "./types";

export const PERIOD_OPTIONS: { value: PeriodKey; label: string }[] = [
  { value: "yesterday", label: "Kemarin" },
  { value: "month1", label: "1 Bulan Lalu" },
  { value: "month3", label: "3 Bulan Lalu" },
];

export const CATEGORY_FILTER_OPTIONS: { value: "all" | InsightItem["category"]; label: string }[] = [
  { value: "all", label: "Semua" },
  { value: "anomali", label: "Anomali" },
  { value: "rekomendasi", label: "Rekomendasi" },
  { value: "positif", label: "Positif" },
];

export const PLATFORM_FILTER_OPTIONS: { value: "all" | "meta" | "tiktok"; label: string }[] = [
  { value: "all", label: "Semua Platform" },
  { value: "meta", label: "Meta Ads" },
  { value: "tiktok", label: "TikTok Ads" },
];

// Template bank per periode: minimal 4 skenario per kategori (anomali/rekomendasi/positif)
// biar filter kategori+platform kombinasi selalu punya isi yang wajar, bukan 1 filler generik.
export const INSIGHT_DATA: Record<PeriodKey, PeriodInsightData> = {
  yesterday: {
    compareLine: "Dibanding 2 hari lalu: 1 anomali baru terdeteksi di TikTok Ads, closing gabungan naik 4%.",
    items: [
      {
        id: "yesterday-anomali-1",
        category: "anomali",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Spend naik, closing stagnan",
        body: "Spend TikTok Ads naik 32% dari kemarin tapi closing cuma naik 4%. Kemungkinan targeting terlalu luas atau creative mulai jenuh.",
        time: "2 jam lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Tinggi",
        impactNote: "Potensi ~Rp450rb spend terbuang tanpa closing tambahan minggu ini bila dibiarkan.",
      },
      {
        id: "yesterday-anomali-2",
        category: "anomali",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "CTR turun mendadak semalam",
        body: "CTR Meta Ads turun dari 3.9% ke 3.2% dalam satu hari — kemungkinan ada campaign yang masuk fase penurunan performa creative.",
        time: "5 jam lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Sedang",
        impactNote: "Kalau berlanjut 2-3 hari lagi, ROAS Meta berpotensi ikut turun.",
      },
      {
        id: "yesterday-anomali-3",
        category: "anomali",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "CPA naik tajam dalam sehari",
        body: "CPA TikTok Ads naik dari Rp58rb ke Rp63rb hanya dalam satu hari — lebih cepat dari pola kenaikan biasanya.",
        time: "7 jam lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Sedang",
        impactNote: "Worth dicek apakah ada campaign baru yang bidding-nya terlalu agresif.",
      },
      {
        id: "yesterday-anomali-4",
        category: "anomali",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "Klik turun meski impresi naik",
        body: "Impresi Meta Ads naik 9% tapi klik cuma naik 2% — rasio klik-terhadap-impresi melemah, tanda audiens mulai bosan dengan creative.",
        time: "10 jam lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Rendah",
        impactNote: "Belum mendesak, tapi worth dipantau 2-3 hari ke depan.",
      },
      {
        id: "yesterday-rekomendasi-1",
        category: "rekomendasi",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "Realokasi budget ke Meta Ads",
        body: "ROAS Meta 26% lebih baik dari TikTok kemarin. Realokasi 15% budget dari TikTok berpotensi menaikkan total closing.",
        time: "4 jam lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Sedang",
        impactNote: "Potensi +8-10 closing tambahan/bulan bila 15% budget dialihkan ke Meta Ads.",
      },
      {
        id: "yesterday-rekomendasi-2",
        category: "rekomendasi",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Refresh creative sebelum performa makin menurun",
        body: "CTR TikTok Ads turun sejak kemarin sementara spend terus naik — waktunya ganti creative sebelum closing makin stagnan.",
        time: "1 hari lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Sedang",
        impactNote: "Berpotensi menahan CTR sebelum turun di bawah 2.5%.",
      },
      {
        id: "yesterday-rekomendasi-3",
        category: "rekomendasi",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "Uji creative baru di jam tayang berbeda",
        body: "Performa terbaik Meta Ads kemarin justru di luar jam tayang utama campaign — worth dites jadwal tayang digeser.",
        time: "1 hari lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Rendah",
        impactNote: "Eksperimen kecil, risiko rendah, potensi tambahan closing dari jam sepi.",
      },
      {
        id: "yesterday-rekomendasi-4",
        category: "rekomendasi",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Sesuaikan bidding otomatis untuk jam sibuk",
        body: "Kompetisi bidding TikTok Ads terlihat lebih ketat di jam 19.00-22.00 — sesuaikan strategi bidding biar spend tidak boros di jam itu.",
        time: "1 hari lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Tinggi",
        impactNote: "Berpotensi menghemat 10-12% spend TikTok Ads tanpa mengorbankan closing.",
      },
      {
        id: "yesterday-positif-1",
        category: "positif",
        platformLabel: "Semua Platform",
        platformKey: "semua",
        title: "CPA membaik dari kemarin",
        body: "Efisiensi biaya akuisisi membaik 6% dibanding kemarin — strategi bidding saat ini masih efektif.",
        time: "6 jam lalu",
        actionLabel: "Lihat Overview →",
        actionHref: "/overview",
        impact: "Rendah",
        impactNote: "Tidak perlu aksi — efisiensi biaya sudah di jalur yang tepat.",
      },
      {
        id: "yesterday-positif-2",
        category: "positif",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "CTR Meta Ads stabil tinggi",
        body: "CTR Meta Ads bertahan di atas 3.5% dua hari berturut-turut — audiens hangat merespons creative dengan baik.",
        time: "1 hari lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Rendah",
        impactNote: "Tidak perlu aksi — pertahankan creative & audiens yang sama.",
      },
      {
        id: "yesterday-positif-3",
        category: "positif",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Closing rate membaik meski spend flat",
        body: "Closing TikTok Ads naik 4% meski spend relatif flat dibanding 2 hari lalu — tanda efisiensi campaign membaik.",
        time: "1 hari lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Sedang",
        impactNote: "Worth dipertahankan — kandidat baik buat dinaikkan budgetnya bertahap.",
      },
      {
        id: "yesterday-positif-4",
        category: "positif",
        platformLabel: "Semua Platform",
        platformKey: "semua",
        title: "Waktu respons iklan ke closing makin cepat",
        body: "Rata-rata waktu dari klik pertama sampai closing memendek dibanding kemarin — funnel checkout terasa makin lancar.",
        time: "2 hari lalu",
        actionLabel: "Lihat Overview →",
        actionHref: "/overview",
        impact: "Rendah",
        impactNote: "Tidak perlu aksi — pertahankan flow checkout yang sekarang.",
      },
    ],
  },
  month1: {
    compareLine: "Dibanding bulan lalu: ROAS gabungan naik 6%, tapi CPA TikTok Ads naik 9% — worth ditinjau.",
    items: [
      {
        id: "month1-anomali-1",
        category: "anomali",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "CPA naik bertahap sepanjang bulan",
        body: "CPA TikTok Ads naik 9% dibanding bulan lalu, tren naik konsisten selama 3 minggu terakhir. Kemungkinan kompetisi bidding meningkat.",
        time: "3 hari lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Tinggi",
        impactNote: "Bila tren berlanjut, CPA berpotensi naik lagi ~9% bulan depan.",
      },
      {
        id: "month1-anomali-2",
        category: "anomali",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "CTR turun di 2 minggu terakhir",
        body: "CTR Meta Ads turun dari 4.1% ke 3.6% dibanding rata-rata bulan lalu — creative fatigue mulai terlihat.",
        time: "5 hari lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Sedang",
        impactNote: "Worth refresh creative sebelum CTR turun di bawah 3%.",
      },
      {
        id: "month1-anomali-3",
        category: "anomali",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Frekuensi iklan per user naik drastis",
        body: "Rata-rata frekuensi tayang iklan TikTok Ads per user naik dari 3.1x ke 4.8x bulan ini — indikasi audiens mulai jenuh lihat iklan yang sama.",
        time: "1 minggu lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Sedang",
        impactNote: "Perluas audiens atau ganti creative sebelum fatigue makin parah.",
      },
      {
        id: "month1-anomali-4",
        category: "anomali",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "Rasio klik-ke-closing turun dibanding bulan lalu",
        body: "Dari 100 klik Meta Ads, closing yang dihasilkan turun dari 3.2 jadi 2.6 dibanding bulan lalu — funnel setelah klik perlu dicek.",
        time: "2 minggu lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Rendah",
        impactNote: "Worth review landing page atau proses checkout dari iklan Meta.",
      },
      {
        id: "month1-rekomendasi-1",
        category: "rekomendasi",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "Naikkan budget campaign performa terbaik",
        body: "3 campaign Meta konsisten ROAS di atas 3x sebulan penuh — worth dinaikkan budgetnya 15-20%.",
        time: "1 minggu lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Tinggi",
        impactNote: "Potensi +15-20% closing tambahan dari 3 campaign top performer.",
      },
      {
        id: "month1-rekomendasi-2",
        category: "rekomendasi",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Uji ulang audiens yang mulai drop",
        body: "Beberapa audiens custom TikTok mengalami penurunan CTR sebulan terakhir — worth diuji ulang dengan segmentasi baru.",
        time: "3 minggu lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Sedang",
        impactNote: "Berpotensi memulihkan CTR lewat segmentasi audiens baru.",
      },
      {
        id: "month1-rekomendasi-3",
        category: "rekomendasi",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "Perluas lookalike audience dari pembeli 30 hari terakhir",
        body: "Pembeli 30 hari terakhir di Meta Ads punya ROAS di atas rata-rata — worth dibuatkan lookalike audience baru buat scaling.",
        time: "3 minggu lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Sedang",
        impactNote: "Potensi memperluas reach ke audiens dengan profil pembeli mirip.",
      },
      {
        id: "month1-rekomendasi-4",
        category: "rekomendasi",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Konsolidasi 2 campaign performa rendah jadi satu",
        body: "2 campaign TikTok Ads dengan target audiens serupa sama-sama underperform sebulan ini — worth digabung biar budget dan data lebih terkonsentrasi.",
        time: "1 bulan lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Rendah",
        impactNote: "Menyederhanakan pengelolaan campaign tanpa menambah risiko besar.",
      },
      {
        id: "month1-positif-1",
        category: "positif",
        platformLabel: "Semua Platform",
        platformKey: "semua",
        title: "ROAS gabungan naik 6% bulan ini",
        body: "Performa lintas platform membaik konsisten dibanding bulan lalu — strategi budget saat ini terbukti efektif.",
        time: "2 minggu lalu",
        actionLabel: "Lihat Overview →",
        actionHref: "/overview",
        impact: "Rendah",
        impactNote: "Tidak perlu aksi — strategi budget saat ini terbukti efektif.",
      },
      {
        id: "month1-positif-2",
        category: "positif",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "Retensi audiens membaik, biaya remarketing turun",
        body: "Biaya remarketing Meta Ads turun 8% bulan ini karena audiens retensi makin besar — funnel lower-stage makin efisien.",
        time: "2 minggu lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Rendah",
        impactNote: "Tidak perlu aksi — pertahankan segmentasi remarketing yang sekarang.",
      },
      {
        id: "month1-positif-3",
        category: "positif",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Engagement rate naik seiring closing",
        body: "Engagement rate TikTok Ads naik seiring naiknya closing bulan ini — sinyal creative yang jalan sekarang memang resonan ke audiens.",
        time: "3 minggu lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Sedang",
        impactNote: "Worth dijadikan acuan gaya creative buat campaign berikutnya.",
      },
      {
        id: "month1-positif-4",
        category: "positif",
        platformLabel: "Semua Platform",
        platformKey: "semua",
        title: "Rasio repeat buyer naik dibanding bulan lalu",
        body: "Porsi closing dari pembeli berulang naik dibanding bulan lalu — tanda loyalitas pelanggan mulai terbangun, bukan cuma akuisisi baru.",
        time: "1 bulan lalu",
        actionLabel: "Lihat Overview →",
        actionHref: "/overview",
        impact: "Rendah",
        impactNote: "Tidak perlu aksi — pertimbangkan program loyalitas buat percepat tren ini.",
      },
    ],
  },
  month3: {
    compareLine: "Dibanding 3 bulan lalu: tren spend naik konsisten +18%, closing rate makin efisien seiring waktu.",
    items: [
      {
        id: "month3-anomali-1",
        category: "anomali",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Fluktuasi performa musiman",
        body: "Performa TikTok Ads naik-turun mengikuti pola akhir pekan sepanjang kuartal ini — pertimbangkan penjadwalan budget mingguan.",
        time: "1 bulan lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Sedang",
        impactNote: "Penjadwalan budget mingguan berpotensi hemat ~10% spend di hari lemah.",
      },
      {
        id: "month3-anomali-2",
        category: "anomali",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "Biaya per klik naik bertahap 3 bulan terakhir",
        body: "CPC Meta Ads naik bertahap tiap bulan selama kuartal ini — kompetisi iklan di kategori Fashion & Retail makin ketat.",
        time: "1 bulan lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Tinggi",
        impactNote: "Bila tren CPC berlanjut, margin per closing berpotensi menipis kuartal depan.",
      },
      {
        id: "month3-anomali-3",
        category: "anomali",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Tingkat penyelesaian video iklan menurun",
        body: "Rata-rata completion rate video TikTok Ads turun dari 68% ke 54% sepanjang kuartal ini — durasi atau hook creative mulai kurang menarik.",
        time: "2 bulan lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Sedang",
        impactNote: "Worth eksperimen hook 3 detik pertama di batch creative berikutnya.",
      },
      {
        id: "month3-anomali-4",
        category: "anomali",
        platformLabel: "Semua Platform",
        platformKey: "semua",
        title: "Ketimpangan performa makin lebar antar platform",
        body: "Gap ROAS antara Meta Ads dan TikTok Ads makin lebar tiap bulan sepanjang kuartal ini — alokasi budget saat ini mulai tidak seimbang dengan performa aktual.",
        time: "2 bulan lalu",
        actionLabel: "Lihat Overview →",
        actionHref: "/overview",
        impact: "Rendah",
        impactNote: "Worth direview ulang saat evaluasi budget kuartal depan.",
      },
      {
        id: "month3-rekomendasi-1",
        category: "rekomendasi",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "Meta jadi kontributor ROAS terbaik",
        body: "Selama 3 bulan terakhir, Meta Ads konsisten jadi platform dengan ROAS tertinggi — pertimbangkan realokasi budget jangka panjang ke Meta.",
        time: "2 bulan lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Tinggi",
        impactNote: "Realokasi budget jangka panjang ke Meta berpotensi naikkan ROAS gabungan.",
      },
      {
        id: "month3-rekomendasi-2",
        category: "rekomendasi",
        platformLabel: "Semua Platform",
        platformKey: "semua",
        title: "Konsolidasikan budget ke jam-jam performa terbaik",
        body: "Data 3 bulan terakhir nunjukin closing paling banyak terjadi di jam 10-13 dan 19-22 — worth budget harian dikonsentrasikan ke jam-jam itu.",
        time: "2 bulan lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Sedang",
        impactNote: "Berpotensi menaikkan efisiensi spend tanpa menambah total budget.",
      },
      {
        id: "month3-rekomendasi-3",
        category: "rekomendasi",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Refresh seluruh set creative kuartal ini",
        body: "Sebagian besar creative TikTok Ads sudah tayang lebih dari 2 bulan tanpa refresh — waktunya rombak batch creative buat kuartal depan.",
        time: "3 bulan lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Sedang",
        impactNote: "Creative baru berpotensi mengembalikan CTR ke level awal kuartal.",
      },
      {
        id: "month3-rekomendasi-4",
        category: "rekomendasi",
        platformLabel: "Semua Platform",
        platformKey: "semua",
        title: "Evaluasi ulang target closing kuartal berikutnya",
        body: "Tren closing 3 bulan terakhir konsisten di atas target lama — worth target closing kuartal depan dinaikkan biar tetap realistis dan menantang.",
        time: "3 bulan lalu",
        actionLabel: "Tandai diterapkan",
        impact: "Rendah",
        impactNote: "Target yang lebih akurat membantu evaluasi performa jadi lebih relevan.",
      },
      {
        id: "month3-positif-1",
        category: "positif",
        platformLabel: "Semua Platform",
        platformKey: "semua",
        title: "Tren spend naik 18% dalam 3 bulan",
        body: "Spend gabungan naik konsisten, diiringi perbaikan efisiensi closing rate — pertumbuhan yang sehat, bukan cuma naik biaya.",
        time: "1 bulan lalu",
        actionLabel: "Lihat Overview →",
        actionHref: "/overview",
        impact: "Rendah",
        impactNote: "Tidak perlu aksi — pertumbuhan sehat, efisiensi closing ikut membaik.",
      },
      {
        id: "month3-positif-2",
        category: "positif",
        platformLabel: "Meta Ads",
        platformKey: "meta",
        title: "CPA membaik bertahap",
        body: "CPA Meta Ads turun perlahan tapi konsisten selama kuartal ini — hasil dari iterasi creative & targeting.",
        time: "2 bulan lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Rendah",
        impactNote: "Tidak perlu aksi — hasil iterasi creative & targeting sudah on track.",
      },
      {
        id: "month3-positif-3",
        category: "positif",
        platformLabel: "TikTok Ads",
        platformKey: "tiktok",
        title: "Konsistensi ROAS terjaga 3 bulan berturut-turut",
        body: "ROAS TikTok Ads tetap stabil di kisaran 2.2x-2.4x sepanjang kuartal, meski sempat ada fluktuasi mingguan — fondasi campaign cukup solid.",
        time: "2 bulan lalu",
        actionLabel: "Lihat platform →",
        actionHref: "/detail",
        impact: "Sedang",
        impactNote: "Worth dipertahankan sambil pelan-pelan tes scaling budget.",
      },
      {
        id: "month3-positif-4",
        category: "positif",
        platformLabel: "Semua Platform",
        platformKey: "semua",
        title: "Biaya akuisisi turun sejalan dengan naiknya loyalitas pelanggan",
        body: "CPA gabungan turun seiring makin banyaknya repeat buyer sepanjang kuartal ini — akuisisi baru makin didukung basis pelanggan setia.",
        time: "3 bulan lalu",
        actionLabel: "Lihat Overview →",
        actionHref: "/overview",
        impact: "Rendah",
        impactNote: "Tidak perlu aksi — tren ini sehat untuk pertumbuhan jangka panjang.",
      },
    ],
  },
};

// Statis (bukan per-periode), sama seperti mockup HTML asli — angka simulasi "rata-rata industri".
export const INDUSTRY_BENCHMARK_CATEGORY = "Fashion & Retail";

export const INDUSTRY_BENCHMARK: BenchmarkMetric[] = [
  {
    name: "ROAS",
    you: 2.7,
    ind: 2.3,
    youText: "2.7x",
    indText: "2.3x",
    higherBetter: true,
    good: "di atas rata-rata industri",
    bad: "di bawah rata-rata industri",
  },
  {
    name: "CPA",
    you: 61,
    ind: 70,
    youText: "Rp61rb",
    indText: "Rp70rb",
    higherBetter: false,
    good: "lebih efisien dari rata-rata industri",
    bad: "lebih mahal dari rata-rata industri",
  },
  {
    name: "CTR",
    you: 3.3,
    ind: 3.6,
    youText: "3.3%",
    indText: "3.6%",
    higherBetter: true,
    good: "di atas rata-rata industri",
    bad: "di bawah rata-rata industri",
  },
];

export const BUDGET_REC: BudgetRecommendation[] = [
  {
    key: "meta",
    cur: 63,
    sug: 72,
    why: "ROAS Meta (2.9x) lebih tinggi dan CPA lebih efisien dibanding TikTok — paling layak dapat tambahan budget.",
  },
  {
    key: "tiktok",
    cur: 37,
    sug: 28,
    why: "Spend naik 32% tapi closing stagnan minggu ini. Tahan dulu sampai creative baru jalan minimal seminggu.",
  },
];
